---
- name: Configure connection profile
  hosts: webserver
  tasks:
    - name: nmcli - configure network
      nmcli:
        conn_name: lab
        type: ethernet
        ifname: enp1s0
        ip4: 192.168.100.200/24
        gw4: 192.168.100.1
        dns4: 192.168.100.1
        state: present




